# Config for grunt-jasmine-nodejs
# https://github.com/onury/grunt-jasmine-nodejs
{
    # task specific (default) options
    options: {
        showColors: true,
        specNameSuffix: 'spec.js', # also accepts an array
        helperNameSuffix: 'helper.js',
        useHelpers: false,
        verboseReport: true
    },
    your_target: {
        # target specific options
        options: {
            useHelpers: true
        },
        # spec files
        specs: [
            "test/**"
        ],
        helpers: [
            "test/helpers/**"
        ]
    }
}